version: '3'
services: 
    app:
        build: .
        ports: 
            - '5000:5000'
        environment: 
            - FLASK_APP=main.py
            - FLASK_ENV=development
        volumes: 
            - ./src:/usr/src/app
